### ISSUE TITLE
How embarrasing of you

### ISSUE THREAD

**Issue by ghost** [TimonPost/GameEngine#1]
Shame on you timon. Why did you write the following on your github profile "1000 LoC .....". I am referring to that silly and stupid word referring to idiots you use after "keeps the". Don't refer to those idiots, and stop being a silly daft slave to them. GROW UP FOR GODS SAKE.

**Comment by HalloEngineer** [comment]
You are not an Engineer as well. you are a silly child who hides behind a keyboard.

**Comment by TimonPost** [comment]
Find some life dude.
